### PR TITLE
Stepper

### PR DESCRIPTION
**Pull request by AbhimanyuAryan**

### CODE REVIEW

**Comment by AbhimanyuAryan** [comment]
```
step("An ad group contains one or more ads which target a shared set of keywords.",
    name! = "2", title="Create an ad group", caption="Optional", icon="create_new_folder", done! = "step > 2"),
```

```
      <q-step
        :name="2"
        title="Create an ad group"
        caption="Optional"
        icon="create_new_folder"
        :done="step > 2"
      >
        An ad group contains one or more ads which target a shared set of keywords.
      </q-step>
 ```

I pushed to the `stepper` branch and it created a duplicate. So I had to close the older branch: https://github.com/GenieFramework/StippleUI.jl/pull/67

**Comment by hhaensel** [comment]
Looks interesting. The docstring should, however, use `qstep()` instead of `step()` because step would conflict with `Base.step()` and some improvements to the docstring are necessary.

**Comment by hhaensel** [comment]
Closed in favour of hh-stepper #119 
Sorry again @AbhimanyuAryan that I struggled with my git and then for time reasons copied your code to my branch.

**Comment by AbhimanyuAryan** [comment]
No problem. I am busy entire Nov-Dec-Jan. I have bandwidth to contribute. But I'll be back 👷

Sorry for not replying to tags 😣

**Pull request closed without merging**
