### PR TITLE
chat component

### PR DESCRIPTION
**Pull request by AbhimanyuAryan**
[❌] - don't merge

Bug: don't render text message

### CODE REVIEW

**Comment by AbhimanyuAryan** [comment]
#88

**Comment by hhaensel** [comment]
Is fixed now :-)

**Comment by hhaensel** [comment]
I chose to render String and Vector{String} arguments directly.
That means if you want to use a string field you have to reference it as a vector
```julia
@app begin
  @out textmsg1 = ["hey, how are you?"]
  @out textmsg2 = "I am good"
end

function ui()
  [
    Html.div(class="q-pa-md row justify-center",[
      Html.div(style="width: 100%; max-width: 400px",[
        chatmessage("This is static text", name="abhi", sent = true)
        chatmessage(:textmsg1, name="abhi", sent = true)
        chatmessage(Symbol("[textmsg2]"), name="adrian")
      ])
    ])
  ]
end
```

**Comment by hhaensel** [comment]
If you are ok with this syntax, let's merge. 🚀

**Comment by hhaensel** [comment]
A chat app would rather apply a Vector of Dict for a chat window, e.g. like this
```julia
using Random

using GenieFramework
@genietools

@app begin
  @in addpost = false
  @out chat = Dict{Symbol, Any}[]

  @onbutton addpost begin
    push!(chat, Dict(:text => [randstring(10) for i in 1:rand(1:3)], :name => randstring(5), :sent => Bool(rand(0:1))))
    notify(chat)
  end
end

function ui()
  [
    cell(class = "st-module q-ma-md q-pa-md", [
        btn("Add message", @click(:addpost), icon = "mail")
        chatmessage(R"d.text", name = R"d.name", sent = R"d.sent", "", @recur("d in chat"))
    ])
  ]
end

p = @page("/", ui)

Server.isrunning() || Server.up()
```

**Comment by AbhimanyuAryan** [comment]
@hhaensel you thought of everything. I don't have anything to add to it. I didn't think of adding `Dict` case with loop. This is perfect. I'll merge

**Comment by AbhimanyuAryan** [comment]
oh and just realized all our stippleui docs is now using deprecated syntax `@reactive` :(

maybe I need do entire dir look up with Regex

```
@reactive! mutable struct xxxxxxx <: xxxxx   # <--- find this pattern in all files
   # code
end
```

replace this with

```
@vars begin  # <---- replace with pattern
   # code
end
``` 

that would be easiest. Adding 

```julia
@app begin
@out ___
@out ___
end
``` 

would require manual updating however :(

**Comment by AbhimanyuAryan** [comment]
Ok no. Even the properties field have ugly R types

```valone::R{Bool} = true```. Will require manual updating :(

**Comment by hhaensel** [comment]
But `@vars` supports both gold Uhl Rtxpe syntax and a modernised one where you don't specify R. Instead you add `NON_REACTIVE` at the end if the Girls should be a simple field.
Since tue ovehaul of the Type these fields can also be readonly or private etc. But update needs to be done manually.

**Comment by AbhimanyuAryan** [comment]
`R_str` ❤️

**Pull request merged**
