### PR TITLE
Jdb/tables fix

### LINKED ISSUE #120: Table filtering stopped working from v0.22.9
In order to perform table filtering, we've been using the following up to StippleUI v0.22.8: 

```julia
Stipple.table(:table_data, class="table-white-row", pagination=:table_page, dense=true, hide__pagination=false, filter=:dfilter,
  template(var"v-slot:top-right"="",
    textfield("", hint="Search by any keywords", :dfilter, borderless="", dense="", debounce="300", placeholder="Search", [
      template(var"v-slot:append"=true,
        icon("search")
      )]
    )
  )
)
```

StipplUI v0.22.9 seems to have have introduce the autogeneration of the above `template` mechanic: https://github.com/GenieFramework/StippleUI.jl/blob/584f88f756b4b35ec292811eac3db613f1b10362/src/Tables.jl#L249-L260
The changed broke the above approach to filtering since the template was now duplicated. 

However, after adapting the call to the following, filtering isn't working. The page displays properly along with the seach box, but there's no reactiv filtering happening when filling the search box:
```julia
Stipple.table(:predicted_positions_table, pagination=:predicted_positions_page, filter=:dfilter, dense=true, hide__pagination=false)
```

The string resulting from this v0.22.10 "broken" filtering is:
 
```
"<q-table :pagination=\"table_page\" :columns=\"table_data.columns\" v-model=\"table_data\" :data=\"table_data.data\" dense 
row-key=\"__id\"><template v-slot:top-right>\n
<q-input dense debounce=\"300\" v-model=\"dfilter\" placeholder=\"Search\">\n    
<template v-slot:append>\n
<q-icon name=\"search\" />\n    
</template>\n  
</q-input>\n
</template>\n
</q-table>"
```

For reference, the valid string resulting from original v0.22.8 table is: 
```
"<q-table row-key=\"__id\" :columns=\"table_data.columns\" v-model=\"table_data\" :data=\"table_data.data\" dense :filter=\"dfilter\" :pagination.sync=\"table_page\"><template v-slot:top-right><q-input debounce=\"300\" hint=\"Search by any keywords\" label v-model=\"dfilter\" borderless placeholder=\"Search\" dense><template v-slot:append><q-icon name=\"search\"></q-icon></template></q-input></template></q-table>"
```

Difference in causing the issue appears to be that ` :filter=\"dfilter\"` is not pushed anymore in the resulting string. Maybe this was caused by the associated work on having server side filtering? Yet I think it would be desirable to maintain support for the original Quasar client-side filtering.

### PR DESCRIPTION
**Pull request by jeremiedb**
Fix #120 #121
This PR overrides the `label` contructor in `active_columns` and `DataTableOptions` with vanilla `string`. 
As for the best way forward, my suggestion would be to rely on an optional user specified vector of columnnames,  but I'd definitly prefer that adhoc modifiers like uppercasing and substitution ("_" => ""). 
Also, since DataFrame supports the handling of non regular variable names (ex: `DataFrame("Nice Name" => 1:2)`), I think it makes the scenario where raw column names from source data are expected as labels (at least by default) quite reasonable. From a user perspective, I think it's easier to reason if there isn't an additonal layer of Tables Interface that acts upon the source table, beyond the well established Tables.jl interface. 

Regardng the fix for adding back `filter` support, the only thing I'm not fully sure is whether this may interfere with the server side filtering support, as I'm not clear whether a server side filtering query would end up actually doing the client side filtering on top of it.

### CODE REVIEW

**Comment by hhaensel** [comment]
@essenciary @PGimenez I like this PR. The existence of clean_label is a bit surprising.
Do you think, people will complain if we remove upcasing?

**Comment by essenciary** [comment]
Yes, it probably makes sense to remove the automatic use of `label_clean` if it causes unexpected/undesired results. The users can call it explicitly if they want. It's probably a breaking change but should not have other impacts than aesthetics. 

@jeremiedb I still need to fix the filtering, I'll get to it soon. It doesn't make sense for server side filtering to also run client side filtering as the server side filtering does the same thing (the client side will have nothing to filter). Maybe it makes sense to have an option to decide between server side and client side filtering.

**Comment by hhaensel** [comment]
@essenciary shouldn't we merge this?
Server-side filtering has been addressed already, right?
@jeremiedb Do you still want to add a change?

**Comment by jeremiedb** [comment]
I'd be happy to the PR merged as it is currently, which keeps the name as extracted from the Tables API. 

Regarding if it's a breaking change, the `label_clean` functionnality was initially introduced in `v0.22.9` so, at least historically, it had not been considered breaking https://github.com/GenieFramework/StippleUI.jl/blob/v0.22.9/src/Tables.jl.

**Comment by hhaensel** [comment]
@essenciary, @PGimenez  I think we should merge this PR. The reasoning is still valide and there's no other refactoring pending anynmore.

**Comment by jeremiedb** [comment]
could it be merged?

**Comment by essenciary** [comment]
Oops, sorry about this @jeremiedb 
@hhaensel please merge if/when you see fit.

**Pull request merged**
