### PR TITLE
 convenience API functions kw, @kw for attributes 

### PR DESCRIPTION
**Pull request by hhaensel**
Make it easier to write modules for new elements.

### CODE REVIEW

**Comment by hhaensel** [comment]
I implemented `kw()` for all UI elements and changed some details in the API which should improve performance.

Two minor points:
- you define a routine `NamedTuple(kwargs::Dict{Symbol, T}) where T` in NamedTuples. At least since Julia 1.6 it is already part of `Base` as `NamedTuple(itr)` in `namedtuple.jl:113`. Do we still support older versions of Julia than 1.6?
- The second constructor in NamedTuples is type piracy, strictly speaking, although this will not do any harm. Should we find a different name for it? (I also found a slightly more performant variant for cases with more than one argument. For a single argument your's is more perfomant.
```julia
NamedTuple(d, x, y) = (d[x] = x ∈ keys(d) ? "$y $(d[x])" : y; NamedTuple(d))
```

Otherwise, I would consider this PR ready for merging.

**Comment by essenciary** [comment]
Thanks, amazing! 

Re `NamedTuple` I don't think it's type piracy. Aren't you providing a new constructor/method? If yes, that's specialisation - the only thing is that we should most likely  define it as `Base.NamedTuple(d, x, y)` in the case (to extend the `Base.NamedTuple` function).

**Comment by hhaensel** [comment]
@essenciary 

Some more remarks:
- I removed @kw, as that did not seem advantageous to me. (Am I right that this would only be beneficial when the macro is inlined? We would need to test this)
- if you don't like the naming `kw()` we could also rewrite your `attributes()` such that it shows the behaviour of `kw` and use `attributes` instead?
- I saw that we have a compat  for Julia of 1.6, so we could remove the definition of `NamedTuple(kwargs::Dict{Symbol, T}) where T`

**Comment by essenciary** [comment]
I see... In this case we can keep the method under Stipple. 

I don't have any issue with `kw` -- it's internal/"private" API anyway. And we can always refactor later. 

Yes, we're targeting Julia 1.6 and up. 

Feel free to merge when you think it's good to go.

**Pull request merged**
