### PR TITLE
add editor

### PR DESCRIPTION
**Pull request by PhilipVinc**
This adds the Editor element from quasar and a few kwargs that it supports.

I needed it for some work and might as well upstream it.

### CODE REVIEW

**Comment by essenciary** [comment]
Fantastic, thanks so much!

**Comment by AbhimanyuAryan** [comment]
`:toolbar`, `:definitions` and `:font` doesn't work as intended

```js
  :toolbar="[
    ['bold', 'italic'],
    ['customItalic'],
    ['save', 'upload'],
    ['spellcheck'],
    ['disabledButton'],
    ['custom_btn']
  ]"
  :definitions="{
    bold: {cmd: 'bold', label: 'Bold', icon: null, tip: 'My bold tooltip'},
    italic: {cmd: 'italic', icon: 'border_color', tip: 'My italic tooltip'},
    customItalic: {cmd: 'italic', icon: 'camera_enhance', tip: 'Italic'},
    save: {tip: 'Save your work', icon: 'save', label: 'Save', handler: saveWork},
    upload: {tip: 'Upload to cloud', icon: 'cloud_upload', label: 'Upload', handler: upload},
    spellcheck: {tip: 'Run spell-check', icon: 'spellcheck', handler: spellCheck},
    disabledButton: {tip: 'I am disabled...', disable: true, icon: 'cloud_off'}
  }"
  ```
  
  What should `JS Object` be mapped to as `Reactive Stipple Element`. Passing `JS Object` as `String` kind of works but 
  
  
  ```julia
  @reactive mutable struct EditorModel <: ReactiveModel
  s_editor::R{String} = "What you see is <b>what</b> you get."
  myfont::R{String} = """{arial: 'Arial', arial_black: 'Arial Black',courier_new: 'Courier New',times_new_roman: 'Times New Roman'}"""
  mytoolbar::R{Vector} = [["bold", "italic"], ["customItalic"], ["save", "upload"], ["spellcheck"], ["disabledButton"], ["custom_btn"]]
  mydef::R{String} = "{ bold: {cmd: 'bold', label: 'Bold', icon: null, tip: 'My bold tooltip'}, italic: {cmd: 'italic', icon: 'border_color', tip: 'My italic tooltip'}, customItalic: {cmd: 'italic', icon: 'camera_enhance', tip: 'Italic'}, save: {tip: 'Save your work', icon: 'save', label: 'Save'}, upload: {tip: 'Upload to cloud', icon: 'cloud_upload', label: 'Upload'}, spellcheck: {tip: 'Run spell-check', icon: 'spellcheck'}, disabledButton: {tip: 'I am disabled...', disable: true, icon: 'cloud_off'} }"
end
```

have to get rid of `handlers` because they crash

`editor(:s_editor, toolbar = :mytoolbar, definitions = :mydef, font = :myfont)`

**Comment by hhaensel** [comment]
I guess they need js functions. You would need to initialise them with `nothing` or with some js like `jsfunction"function() {console.log('Hi')}"`. I might have a look later.

**Comment by hhaensel** [comment]
Just reading this from my mobile...
You could define the handlers as jsmethods or directly with jsfunction as mentioned above.
Furthermore, I'd rather use Dict to store the values than a string

**Comment by hhaensel** [comment]
Now!
Here's the example code that I uploaded also to StippleDemos.
```julia
using Stipple, StippleUI
import Stipple.opts

@reactive! mutable struct Test <: ReactiveModel
    s_editor::R{String} = "What you see is <b>what</b> you get."
    myfont::R{Dict{Symbol, Any}} = opts(
        arial = "Arial",
        arial_black = "Arial Black",
        courier_new = "Courier New",
        times_new_roman = "Times New Roman"
    )
    mytoolbar::R{Vector{Vector{Union{Symbol,String}}}} = [
        [:bold, :italic],
        [:customItalic], 
        ["save", "upload"],
        ["spellcheck"],
        ["disabledButton"],
        ["custom_btn"]
    ]
    mydef::R{Dict{Symbol, Any}} = opts(
        bold = opts(cmd = "bold", label = "Bold", icon = nothing, tip = "My bold tooltip"),
        italic = opts(cmd = :italic, icon = "border_color", tip = "My italic tooltip"),
        customItalic = opts(cmd = :italic, icon = :camera_enhance, tip = "Italic"),
        save = opts(
            tip = "Save your work", icon = :save, label = "Save", 
            handler = jsfunction"Test.$q.notify({type: 'positive', message: 'I saved your work!'})"
        ),
        upload = opts(tip = "Upload to cloud", icon = "cloud_upload", label = "Upload",
            handler = jsfunction"Test.upload()"
        ),
        spellcheck = opts(tip = "Run spell-check", icon = "spellcheck"),
        disabledButton = opts(tip = "I am disabled...", disable = true, icon = "cloud_off")
    )
end

Stipple.js_methods(::Test) = raw"""
    upload: function() { this.$q.notify({
        type: 'negative',
        message: 'Error during upload, no destination specified!'
    }) }
"""

function handlers(model)
    on(model.isready) do isready
        isready || return
        @async begin
            sleep(0.2)
            push!(model)
        end
    end

    model
end

model = init(Test, debounce = 0) |> handlers

function ui(model)
    page(model, class = "container", row(cell(class = "st-module", row([
        editor(:s_editor, toolbar = :mytoolbar, definitions = :mydef, font = :myfont)
    ]))), @iif(:isready)) |> html
end

route("/") do 
    global model
    ui(model)
end

up(8000, open_browser=true)
```
grafik

**Comment by hhaensel** [comment]
Note:
- I used mixed notations, sometimes strings, sometimes symbols. On the client side all are rendered as strings.
- for calling `$q.notify` one needs to prefix it with the name of the model type, which is `vm(MyReactiveType)` in general and `Test` in this particular example.
- One could also define the editor settings later, or use predefined variables, if this looks bulky in definition of the model

**Comment by AbhimanyuAryan** [comment]
> Note:
> - I used mixed notations, sometimes strings, sometimes symbols. On the client side all are rendered as strings.
> - for calling `$q.notify` one needs to prefix it with the name of the model type, which is `vm(MyReactiveType)` in general and `Test` in this particular example.
> - One could also define the editor settings later, or use predefined variables, if this looks bulky in definition of the model

Woah thanks @hhaensel this is amazing

**Comment by hhaensel** [comment]
At this occasion I added a method for notify

```julia
notify(model::ReactiveModel, message::AbstractString, type::Union{Symbol, String, Nothing} = nothing; kwargs...)
```
for displaying a notification on the client by using Quasar's `$q.notify`.
Types are e.g. `:positive`, `:negative`, `:waring`, `:info`, `:ongoing`.
All other arguments to `$q.notify` are supported via keyword arguments

### Example
`notify(model, "Hello world!", :positive, icon = :tag_faces, caption = "5 minutes ago")`

It's part of `Stipple#master` 😄

**Comment by AbhimanyuAryan** [comment]
Yea I will include this in docs 🤙

**Comment by hhaensel** [comment]
Is there a site for the docs already?

**Comment by AbhimanyuAryan** [comment]
> Is there a site for the docs already?

The docs will on `https://www.genieframework.com/docs/` possibly on Tuesday. There's a stipple section so it will be `https://www.genieframework.com/docs/stipple`

**Comment by hhaensel** [comment]
Is it maintained on github?

**Comment by AbhimanyuAryan** [comment]
> Is it maintained on github?

Yes it's on GitHub. Plans to open-source it soon after the structure is fixed(maybe after Stipple, StippleUI and SearchLight docs)

**Pull request merged**
