### PR TITLE
Added Support for Tabs in StippleUI Pages

### PR DESCRIPTION
**Pull request by TheCedarPrince**
Beginning to add support for tabs in StippleUIs for navigation purposes.
Followed instructions from Abhi but am not sure if I did it quite right.
I registered all properties for all the Quasar Tabs here: https://v1.quasar.dev/vue-components/tabs

Let me know if I need to adjust or fix anything.
Right now, I am testing to figure out how to use it.
Thanks!

CC @AbhimanyuAryan and @essenciary

### CODE REVIEW

**Comment by AbhimanyuAryan** [comment]
sure @TheCedarPrince I'll test it and will merge

**Comment by AbhimanyuAryan** [comment]
@TheCedarPrince you don't need to map 

```
  "href" => "href",
  "icon" => "icon",
```
etc .... Can you modify it?

**Comment by TheCedarPrince** [comment]
Hey @AbhimanyuAryan - I removed those two attributes!
Anything else need to be done here?

**Comment by AbhimanyuAryan** [comment]
@TheCedarPrince `"breakpoint" => "breakpoint"` remove any attribute that does have `-` and doesn't need mapping. Also why have you removed `max-height`. This has `-` it needs mapping

**Comment by TheCedarPrince** [comment]
@AbhimanyuAryan - `max-height` is still there and I removed the other attributes that did not have the `-` character initially.
Should it work now?
I still do not know how to get it working on my machine at this time to test. 🙁

**Comment by AbhimanyuAryan** [comment]
also you can see `Tabs` and `Tab` are different. You need to come up with better naming. `module Tabs` is confusing. Maybe use `STabs` for single Tab or `MTabs` for multiple tabs 

You need to come up with better naming for Tabs API: https://v1.quasar.dev/vue-components/tabs

Maybe @hhaensel can drop his valuable feedback for better naming

**Comment by AbhimanyuAryan** [comment]
also @TheCedarPrince when you run the app. You see html page source to see if element is rendering correctly or not

**Comment by TheCedarPrince** [comment]
> also you can see `Tabs` and `Tab` are different. You need to come up with better naming. `module Tabs` is confusing. Maybe use `STabs` for single Tab or `MTabs` for multiple tabs

Ah.
So these attributes I added were for all the different tab types listed here: https://v1.quasar.dev/vue-components/tabs
Should I instead make three separate PRs for each respective tab type (i.e. `Tabs`, `Tab`, and `RouteTab`)? 

> also @TheCedarPrince when you run the app. You see html page source to see if element is rendering correctly or not

So I haven't been able to do that yet to see if the element is running.
Here was the code I attempted to use:

```julia
using Stipple, StippleUI

@reactive mutable struct Model <: ReactiveModel
    tab_name::R{String} = "Tabby"
end

function ui(my_model)
  page(
    my_model, class="container", [
      tab(label = "FOO"),
    ],
  )
end

my_model = Stipple.init(Model)

route("/") do 
  html(ui(my_model), context = @__MODULE__)
end
```

Does my branch not work for you?

**Comment by AbhimanyuAryan** [comment]
@TheCedarPrince sure I'll pull and check later today. Give me sometime

**Comment by TheCedarPrince** [comment]
Ah ok, I had a look at the output also using the console inspector.
It would appear I need to define a `Tabs` module as well and make all `Tab` objects as children of that.
I have no idea how to do that. 😬 

image

**Comment by AbhimanyuAryan** [comment]
Looks good on my side. Compiled and shows the correct `q-tab` in page source

Screenshot 2022-01-28 at 12 08 18 PM

**Comment by AbhimanyuAryan** [comment]
But as you can see the console error. The `q-tab` needs to a child element of `q-tabs`

```
      <q-tabs
        v-model="tab"
        dense
        class="bg-grey-2 text-teal"
      >
        <q-tab name="mails" icon="mail" label="Mails" />
        <q-tab name="alarms" icon="alarm" label="Alarms" />
        <q-tab name="movies" icon="movie" label="Movies" />
      </q-tabs>
```

So you need to add support for `q-tabs` as well and then pass `q-tab` as nested component 

Screenshot 2022-01-28 at 12 13 04 PM

**Comment by AbhimanyuAryan** [comment]
Here's what I modifed in `q-tabs` implementation. So `STabs` modules is implements for Single Tab. Maybe you can add support for `MTabs` which is multiple tabs.

Screenshot 2022-01-28 at 12 09 15 PM

**Comment by AbhimanyuAryan** [comment]
Example of how to use nested elements: https://github.com/GenieFramework/StippleUI.jl/issues/41

**Comment by AbhimanyuAryan** [comment]
Also this example has `spinner` component as nested element of `imageview`. Quasar complement of this is: ```<q-img> <q-spinner></q-spinner> </q-img>``` <--- something like that


https://github.com/GenieFramework/StippleDemos/blob/1fbd312947199f30f9931963b999cec02590e6f5/BasicExamples/ImageGallery.jl#L42


Looking forward to you first PR in *StippleUI*. Let me know if anything not clear :D

**Comment by TheCedarPrince** [comment]
Hey @AbhimanyuAryan , 

That worked perfectly!
Here is a little video of it working:

https://user-images.githubusercontent.com/29561456/151644931-d2437b3f-1efb-42d3-99e0-a41bab90e66f.mov

I decided to go with `tab` instead of `stab` and used `mtab` for multiple tabs.
However, if you notice, the center tab labeled "BAZ" does not get highlighted.
This is because it is a router tab, `rtab`, and is not connected to the Vue Router or Genie Router and fails to go to another page; it fails completely.
I do not know how to get that functionality working as that was the functionality I was most desirous to have so I could easily navigate to other pages in a clickable way.

The question on routing tabs seems most related to issue #32 and in particular, the discussion here: https://github.com/GenieFramework/StippleUI.jl/issues/32#issuecomment-961697450 between @hhaensel and @essenciary 
I certainly would rather prefer to stick to the Genie router instead of the Genie router but do not know how to do that.
Any thoughts or help here?
Thanks!

**Comment by TheCedarPrince** [comment]
Hey @AbhimanyuAryan, this wasn't ready to be merged.
It just introduced a bug into StippleUI and doesn't actually do what I need it to do either yet.
Were you going to open another issue and PR to fix QRouteTab?

**Comment by AbhimanyuAryan** [comment]
@TheCedarPrince I noticed `rtab` bug  now. I reverted the pull request. Yes let's fix the bug and then merge

**Comment by TheCedarPrince** [comment]
Sounds great @AbhimanyuAryan !
I'll open a new PR off of this branch.
Do you have any idea on how to address what I was saying here: 

> I decided to go with tab instead of stab and used mtab for multiple tabs.
However, if you notice, the center tab labeled "BAZ" does not get highlighted.
This is because it is a router tab, rtab, and is not connected to the Vue Router or Genie Router and fails to go to another page; it fails completely.
I do not know how to get that functionality working as that was the functionality I was most desirous to have so I could easily navigate to other pages in a clickable way.

> The question on routing tabs seems most related to issue #32 and in particular, the discussion here: #32 (comment) between @hhaensel and @essenciary
I certainly would rather prefer to stick to the Genie router instead of the Genie router but do not know how to do that.
Any thoughts or help here?
Thanks!

**Comment by AbhimanyuAryan** [comment]
@TheCedarPrince you can solve this with a hacky solution i.e. `redirect`. Where you can redirect to a route on tab click which `\about` let's say renders a different stipple view. But as I said this is hacky

The best way to solve this is add support for frontend routing and let vue-router/stipple-router handle it which doesn't trigger Genie routing. That will also be faster and more efficient

**Comment by AbhimanyuAryan** [comment]
Let me think over it and come up with a solution

**Pull request merged**
